version: '3.8'
services:
  app:
    build: .
    container_name: my-nest-project-app-1
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: yeonhashin
      DB_PASSWORD: 1234
      DB_DATABASE: my_nest_project_db

  db:
    image: postgres:15
    container_name: my-postgres
    environment:
      POSTGRES_USER: yeonhashin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: my_nest_project_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
